import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import api from '../services/api'

const PendingApprovalsAdmin = () => {
  const [pendingTimetables, setPendingTimetables] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchPendingTimetables()
  }, [])

  const fetchPendingTimetables = async () => {
    try {
      setLoading(true)
      const response = await api.get('/timetable')
      const pending = response.data.filter(t => t.status === 'PENDING')
      setPendingTimetables(pending)
    } catch (error) {
      console.error('Error fetching pending timetables:', error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <h1 className="text-3xl font-bold text-gray-900">Pending Approvals (Admin View)</h1>

      {loading ? (
        <div className="flex items-center justify-center py-8">
          <div className="w-8 h-8 border-4 border-primary-600 border-t-transparent rounded-full animate-spin"></div>
          <span className="ml-2 text-gray-600">Loading pending approvals...</span>
        </div>
      ) : pendingTimetables.length > 0 ? (
        <div className="grid gap-4">
          {pendingTimetables.map((timetable) => (
            <motion.div
              key={timetable._id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="card border-l-4 border-l-yellow-500"
            >
              <div className="flex justify-between items-start">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <h3 className="text-xl font-semibold text-gray-900">
                      {timetable.sectionId?.sectionName || 'Unknown Section'}
                    </h3>
                    <span className="bg-yellow-100 text-yellow-800 px-2 py-1 rounded-full text-xs font-medium">
                      PENDING HOD APPROVAL
                    </span>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4 text-sm text-gray-600">
                    <div>
                      <p><span className="font-medium">Generated by:</span> {timetable.generatedBy?.name}</p>
                      <p><span className="font-medium">Academic Year:</span> {timetable.academicYear}</p>
                    </div>
                    <div>
                      <p><span className="font-medium">Semester:</span> {timetable.semester}</p>
                      <p><span className="font-medium">Created:</span> {new Date(timetable.createdAt).toLocaleDateString()}</p>
                    </div>
                  </div>
                  
                  <div className="mt-3 flex items-center gap-4 text-sm">
                    <span className="bg-blue-100 text-blue-800 px-2 py-1 rounded">
                      📅 {timetable.slots?.length || 0} Time Slots
                    </span>
                    <span className="bg-purple-100 text-purple-800 px-2 py-1 rounded">
                      🏢 Awaiting HOD Review
                    </span>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      ) : (
        <div className="text-center py-12">
          <div className="w-24 h-24 mx-auto mb-4 bg-gray-100 rounded-full flex items-center justify-center">
            <span className="text-4xl">✅</span>
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">No Pending Approvals</h3>
          <p className="text-gray-600 mb-4">All timetables have been reviewed by HODs.</p>
        </div>
      )}
    </motion.div>
  )
}

export default PendingApprovalsAdmin